/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ase.polizas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Rodriguez Santiago Yazmin L.
 */
public class Dashboard extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        Principal p = new Principal();
        p.setSize(850, 480);
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/exe.png")).getImage());
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/ase/polizas/img/excel.ico")));
        
        Content.removeAll();
        Content.add(p, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        nameApp = new javax.swing.JLabel();
        btn_ingresos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_principal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_egresos = new javax.swing.JPanel();
        separadorNameApp1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        separadorNameApp2 = new javax.swing.JSeparator();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 550));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMaximumSize(new java.awt.Dimension(850, 550));
        Background.setMinimumSize(new java.awt.Dimension(850, 550));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameApp.setBackground(new java.awt.Color(255, 255, 255));
        nameApp.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        nameApp.setForeground(new java.awt.Color(255, 255, 255));
        nameApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameApp.setText("Pólizas Contables");
        Menu.add(nameApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_ingresos.setBackground(new java.awt.Color(18, 90, 173));
        btn_ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingresosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_ingresosMouseReleased(evt);
            }
        });
        btn_ingresos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/excel_blue.png"))); // NOI18N
        jLabel1.setText(" Pólizas de Ingresos");
        btn_ingresos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Menu.add(btn_ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 230, 70));

        btn_principal.setBackground(new java.awt.Color(21, 101, 192));
        btn_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_principalMousePressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_principalLayout = new javax.swing.GroupLayout(btn_principal);
        btn_principal.setLayout(btn_principalLayout);
        btn_principalLayout.setHorizontalGroup(
            btn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_principalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btn_principalLayout.setVerticalGroup(
            btn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_principalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Menu.add(btn_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 60, -1));

        btn_egresos.setBackground(new java.awt.Color(18, 90, 173));
        btn_egresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_egresosMousePressed(evt);
            }
        });
        btn_egresos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separadorNameApp1.setBackground(new java.awt.Color(255, 255, 255));
        separadorNameApp1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separadorNameApp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        separadorNameApp1.setMinimumSize(new java.awt.Dimension(5, 5));
        btn_egresos.add(separadorNameApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/excel_purple.png"))); // NOI18N
        jLabel3.setText(" Pólizas de Egresos");
        btn_egresos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Menu.add(btn_egresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 230, 70));

        separadorNameApp2.setBackground(new java.awt.Color(255, 255, 255));
        separadorNameApp2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separadorNameApp2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        separadorNameApp2.setMinimumSize(new java.awt.Dimension(5, 5));
        Menu.add(separadorNameApp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 10, 50));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 70));

        Content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        Background.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresosMousePressed
        resetColor(btn_principal);
        resetColor(btn_egresos);
        setColor(btn_ingresos);
        Ingresos i = new Ingresos();
        i.setSize(850, 480);
        i.setLocation(0,0);
        
        Content.removeAll();
        Content.add(i, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_ingresosMousePressed

    private void btn_principalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_principalMousePressed
        resetColor(btn_ingresos);
        resetColor(btn_egresos);
        setColor(btn_principal);
        
        Principal p = new Principal();
        p.setSize(850, 480);
        p.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_principalMousePressed

    private void btn_egresosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_egresosMousePressed
        resetColor(btn_principal);
        resetColor(btn_ingresos);
        setColor(btn_egresos);
        Egresos e = new Egresos();
        e.setSize(850, 480);
        e.setLocation(0,0);
        
        Content.removeAll();
        Content.add(e, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_egresosMousePressed

    private void btn_ingresosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresosMouseReleased
    /**
     * Asignación de color a un panel
     * @param panel 
     */    
    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    /**
     * Reseteo de color a un panel
     * @param panel 
     */
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel btn_egresos;
    private javax.swing.JPanel btn_ingresos;
    private javax.swing.JPanel btn_principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nameApp;
    private javax.swing.JSeparator separadorNameApp1;
    private javax.swing.JSeparator separadorNameApp2;
    // End of variables declaration//GEN-END:variables
}
