/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ase.polizas;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rodriguez Santiago Yazmin L.
 */
public class Egresos extends javax.swing.JPanel {

    static JavaPoiUtils jpu = new JavaPoiUtils();

    /**
     * Creates new form Egresos
     */
    public Egresos() {
        initComponents();
        btn_layout.setEnabled(false);
        btn_layout.setBackground(Color.white);
        grupo_botones.add(normal);
        grupo_botones.add(cliente);
        grupo_botones.setSelected(normal.getModel(), true);
        gif_label.setVisible(false);
    }

    public void verificarArchivos() {
        if (jpu.getCatalogo() != null & jpu.getPrefactura() != null) {
            btn_layout.setEnabled(true);
            btn_layout.setBackground(Color.green);
        }else{
            btn_layout.setBackground(Color.red);
        }
    }

    /**
     * Método que regresa el archivo selecionado en tipo File
     *
     * @return String
     */
    public File seleccionarArchivo() {
        JFileChooser fileChooser = new JFileChooser(".");
        FileFilter filtro = new FileNameExtensionFilter("Archivos xlsx (.xlsx)", "xlsx");
        fileChooser.setFileFilter(filtro);
        int valor = fileChooser.showOpenDialog(fileChooser);
        if (valor == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            File f = new File(ruta);
            System.out.println("Se ha selecionado el archivo");
            return f;
        } else {
            System.out.println("No se ha selecionado el archivo");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        btn_prefacturas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_conciliacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_catalogo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        selecciona_catalogo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        selecciona_conciliacion = new javax.swing.JLabel();
        btn_layout = new javax.swing.JButton();
        conciliacion_texto = new javax.swing.JLabel();
        catalogo_texto = new javax.swing.JLabel();
        prefactura_texto = new javax.swing.JLabel();
        selcciona_prefactura = new javax.swing.JLabel();
        cliente = new javax.swing.JRadioButton();
        normal = new javax.swing.JRadioButton();
        recordatorio = new javax.swing.JLabel();
        gif_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(850, 480));
        setMinimumSize(new java.awt.Dimension(850, 480));
        setName("background"); // NOI18N
        setRequestFocusEnabled(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMaximumSize(new java.awt.Dimension(850, 480));
        Background.setMinimumSize(new java.awt.Dimension(850, 480));
        Background.setPreferredSize(new java.awt.Dimension(850, 480));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_prefacturas.setBackground(new java.awt.Color(0, 204, 51));
        btn_prefacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_prefacturasMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/icon_excel.png"))); // NOI18N
        jLabel1.setText("  Prefactura");
        btn_prefacturas.add(jLabel1);

        Background.add(btn_prefacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 240, 40));

        btn_conciliacion.setBackground(new java.awt.Color(0, 51, 204));
        btn_conciliacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_conciliacionMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/icon_bank.png"))); // NOI18N
        jLabel3.setText("Conciliación Bancaria");
        btn_conciliacion.add(jLabel3);

        Background.add(btn_conciliacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 240, 40));

        btn_catalogo.setBackground(new java.awt.Color(102, 102, 255));
        btn_catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_catalogoMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/icon_catalog.png"))); // NOI18N
        jLabel5.setText("Catálogo de Cuentas");
        btn_catalogo.add(jLabel5);

        Background.add(btn_catalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 40));

        selecciona_catalogo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        selecciona_catalogo.setText("Selecciona tu catálogo de cuentas");
        Background.add(selecciona_catalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Tipo de póliza");
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 160, -1));

        selecciona_conciliacion.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        selecciona_conciliacion.setText("Selecciona tu conciliación");
        Background.add(selecciona_conciliacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 210, 20));

        btn_layout.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btn_layout.setText("Generar Layout");
        btn_layout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_layout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_layoutActionPerformed(evt);
            }
        });
        Background.add(btn_layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 150, 40));

        conciliacion_texto.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        conciliacion_texto.setForeground(new java.awt.Color(153, 153, 153));
        conciliacion_texto.setText("No se ha seleccionado ningún archivo");
        Background.add(conciliacion_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 250, 20));

        catalogo_texto.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        catalogo_texto.setForeground(new java.awt.Color(153, 153, 153));
        catalogo_texto.setText("No se ha seleccionado ningún archivo");
        Background.add(catalogo_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        prefactura_texto.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        prefactura_texto.setForeground(new java.awt.Color(153, 153, 153));
        prefactura_texto.setText("No se ha seleccionado ningún archivo");
        Background.add(prefactura_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, 20));

        selcciona_prefactura.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        selcciona_prefactura.setText("Selecciona tu prefactura");
        Background.add(selcciona_prefactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 200, -1));

        cliente.setBackground(new java.awt.Color(255, 255, 255));
        cliente.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cliente.setText("NÓMINA + CLIENTE");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        Background.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        normal.setBackground(new java.awt.Color(255, 255, 255));
        normal.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        normal.setText("NÓMINA + ID");
        Background.add(normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        recordatorio.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        recordatorio.setForeground(new java.awt.Color(255, 0, 0));
        recordatorio.setText("VERIFICA QUE TUS ARCHIVOS CONTENGAN LA INFORMACIÓN EN LA HOJA UNO");
        Background.add(recordatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        gif_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gif_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/loading4.gif"))); // NOI18N
        Background.add(gif_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 100, 80));

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EGRESOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel2)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("BackGround");
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que realiza la lectura de la prefactura
     *
     * @param evt
     */
    private void btn_prefacturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prefacturasMousePressed
        jpu.setPrefactura(null);
        File archivo = seleccionarArchivo();
        if (archivo != null) {
            jpu.setPrefactura(jpu.trasformaWB(archivo));
            prefactura_texto.setText("Prefactura agregada");
            prefactura_texto.setForeground(btn_prefacturas.getBackground());
            verificarArchivos();
        } else {
            prefactura_texto.setText("Error, selecciona nuevamente");
            prefactura_texto.setForeground(Color.RED);
        }
    }//GEN-LAST:event_btn_prefacturasMousePressed

    private void btn_catalogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_catalogoMousePressed
        jpu.setCatalogo(null);
        File archivo = seleccionarArchivo();
        if (archivo != null) {
            jpu.getCuentasList().clear();
            jpu.setCatalogo(jpu.trasformaWB(archivo));
            jpu.leerCatalogo();
            if (!jpu.getCuentasList().isEmpty()) {
                catalogo_texto.setText("Catálogo agregado");
                catalogo_texto.setForeground(btn_prefacturas.getBackground());
                //jpu.leerCuentas();
            } else {
                catalogo_texto.setText("Error, selecciona nuevamente");
                catalogo_texto.setForeground(Color.RED);
            }
            verificarArchivos();
        } else {
            catalogo_texto.setText("No se ha seleccionado ningún archivo");
            catalogo_texto.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_catalogoMousePressed

    private void btn_conciliacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_conciliacionMousePressed
        jpu.setConciliación(null);
        File archivo = seleccionarArchivo();
        if (archivo != null) {
            jpu.setConciliación(jpu.trasformaWB(archivo));
            conciliacion_texto.setText("Conciliación agregada");
            conciliacion_texto.setForeground(btn_prefacturas.getBackground());
            verificarArchivos();
        } else {
            conciliacion_texto.setText("No se ha seleccionado ningún archivo");
            conciliacion_texto.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_conciliacionMousePressed

    private void btn_layoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_layoutActionPerformed
        if (normal.isSelected()) {
            jpu.setTipo_poliza(true);
        } else {
            jpu.setTipo_poliza(false);
        }
        new Cargar().show();
    }//GEN-LAST:event_btn_layoutActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed

    }//GEN-LAST:event_clienteActionPerformed

    public class Cargar implements Runnable {
        public void show() {
            new Thread(this).start();
        }

        public void run() {
            gif_label.setVisible(true);
            //jpu.leerCuentas();
            jpu.createExcel();
            while (jpu.getFinalizado() != true) {

            }
            gif_label.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel btn_catalogo;
    private javax.swing.JPanel btn_conciliacion;
    private javax.swing.JButton btn_layout;
    private javax.swing.JPanel btn_prefacturas;
    private javax.swing.JLabel catalogo_texto;
    private javax.swing.JRadioButton cliente;
    private javax.swing.JLabel conciliacion_texto;
    private javax.swing.JLabel gif_label;
    private javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton normal;
    private javax.swing.JLabel prefactura_texto;
    private javax.swing.JLabel recordatorio;
    private javax.swing.JLabel selcciona_prefactura;
    private javax.swing.JLabel selecciona_catalogo;
    private javax.swing.JLabel selecciona_conciliacion;
    // End of variables declaration//GEN-END:variables
}
