/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ase.polizas;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author obx
 */
public class Ingresos extends javax.swing.JPanel {

    static JavaPoiUtilsIngresos jpui = new JavaPoiUtilsIngresos();

    /**
     * Creates new form Ingresos
     */
    public Ingresos() {
        initComponents();
        btn_layout_ingresos.setEnabled(false);
        btn_layout_ingresos.setBackground(Color.white);
        grupo_botones.add(normal);
        grupo_botones.add(cliente);
        grupo_botones.setSelected(normal.getModel(), true);
        gif_label.setVisible(false);
    }

    public void verificarArchivos() {
        if (jpui.getCatalogo() != null & jpui.getConciliacion() != null) {
            btn_layout_ingresos.setEnabled(true);
            btn_layout_ingresos.setBackground(Color.green);
        }else{
            btn_layout_ingresos.setBackground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        btn_catalogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selecciona_conciliacion = new javax.swing.JLabel();
        conciliación = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        selecciona_catalogo = new javax.swing.JLabel();
        conciliacion_texto = new javax.swing.JLabel();
        catalogo_texto = new javax.swing.JLabel();
        btn_layout_ingresos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        normal = new javax.swing.JRadioButton();
        cliente = new javax.swing.JRadioButton();
        gif_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        recordatorio = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(850, 480));
        setMinimumSize(new java.awt.Dimension(850, 480));
        setPreferredSize(new java.awt.Dimension(850, 480));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMaximumSize(new java.awt.Dimension(850, 480));
        Background.setMinimumSize(new java.awt.Dimension(850, 480));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_catalogo.setBackground(new java.awt.Color(102, 102, 255));
        btn_catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_catalogoMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/icon_catalog.png"))); // NOI18N
        jLabel1.setText("Catálogo de Cuentas");
        btn_catalogo.add(jLabel1);

        Background.add(btn_catalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 40));

        selecciona_conciliacion.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        selecciona_conciliacion.setText("Selecciona tu conciliación");
        Background.add(selecciona_conciliacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        conciliación.setBackground(new java.awt.Color(0, 204, 51));
        conciliación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                conciliaciónMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/icon_excel.png"))); // NOI18N
        jLabel3.setText("Conciliación de ingresos");
        conciliación.add(jLabel3);

        Background.add(conciliación, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 240, 40));

        selecciona_catalogo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        selecciona_catalogo.setText("Selecciona tu catálogo de cuentas");
        Background.add(selecciona_catalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        conciliacion_texto.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        conciliacion_texto.setForeground(new java.awt.Color(153, 153, 153));
        conciliacion_texto.setText("No se ha seleccionado ningún archivo");
        Background.add(conciliacion_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 20));

        catalogo_texto.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        catalogo_texto.setForeground(new java.awt.Color(153, 153, 153));
        catalogo_texto.setText("No se ha seleccionado ningún archivo");
        Background.add(catalogo_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, 20));

        btn_layout_ingresos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btn_layout_ingresos.setText("Generar Layout");
        btn_layout_ingresos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_layout_ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_layout_ingresosActionPerformed(evt);
            }
        });
        Background.add(btn_layout_ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 150, 40));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Tipo de póliza");
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 160, -1));

        normal.setBackground(new java.awt.Color(255, 255, 255));
        normal.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        normal.setText("NÓMINA + ID");
        Background.add(normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 20));

        cliente.setBackground(new java.awt.Color(255, 255, 255));
        cliente.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cliente.setText("NÓMINA + CLIENTE");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        Background.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        gif_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gif_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ase/polizas/img/loading4.gif"))); // NOI18N
        Background.add(gif_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 110, 90));

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INGRESOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(371, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(367, 367, 367))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        recordatorio.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        recordatorio.setForeground(new java.awt.Color(255, 0, 0));
        recordatorio.setText("VERIFICA QUE TUS ARCHIVOS CONTENGAN LA INFORMACIÓN EN LA HOJA UNO");
        Background.add(recordatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que regresa el archivo selecionado en tipo File
     *
     * @return String
     */
    public File seleccionarArchivo() {
        JFileChooser fileChooser = new JFileChooser(".");
        FileFilter filtro = new FileNameExtensionFilter("Archivos xlsx (.xlsx)", "xlsx");
        fileChooser.setFileFilter(filtro);
        int valor = fileChooser.showOpenDialog(fileChooser);
        if (valor == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            File f = new File(ruta);
            System.out.println("Se ha selecionado el archivo");
            return f;
        } else {
            System.out.println("No se ha selecionado el archivo");
            return null;
        }
    }

    private void btn_layout_ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_layout_ingresosActionPerformed
        if (normal.isSelected()) {
            jpui.setTipo_poliza(true);
        } else {
            jpui.setTipo_poliza(false);
        }
        new Cargar().show();
    }//GEN-LAST:event_btn_layout_ingresosActionPerformed

    private void btn_catalogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_catalogoMousePressed
        jpui.setCatalogo(null);
        File archivo = seleccionarArchivo();
        if (archivo != null) {
            jpui.getCuentasList().clear();
            jpui.setCatalogo(jpui.trasformaWB(archivo));
            jpui.leerCatalogo();
            if (!jpui.getCuentasList().isEmpty()) {
                catalogo_texto.setText("Catálogo agregado");
                catalogo_texto.setForeground(Color.GREEN);
                jpui.leerCuentas();
            } else {
                catalogo_texto.setText("Error, selecciona nuevamente");
                catalogo_texto.setForeground(Color.RED);
            }
            verificarArchivos();
        } else {
            catalogo_texto.setText("No se ha seleccionado ningún archivo");
            catalogo_texto.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_catalogoMousePressed

    private void conciliaciónMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conciliaciónMousePressed
        jpui.setConciliacion(null);
        File archivo = seleccionarArchivo();
        if (archivo != null) {
            jpui.setConciliacion(jpui.trasformaWB(archivo));
            conciliacion_texto.setText("Conciliación agregada");
            conciliacion_texto.setForeground(Color.GREEN);
            verificarArchivos();
        } else {
            conciliacion_texto.setText("No se ha seleccionado ningún archivo");
            conciliacion_texto.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_conciliaciónMousePressed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed

    }//GEN-LAST:event_clienteActionPerformed

    public class Cargar implements Runnable {
        public void show() {
            new Thread(this).start();
        }

        public void run() {
            gif_label.setVisible(true);
            //jpui.CrearPolizas();
            jpui.createExcel();
            while (jpui.getFinalizado() != true) {

            }
            gif_label.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel btn_catalogo;
    private javax.swing.JButton btn_layout_ingresos;
    private javax.swing.JLabel catalogo_texto;
    private javax.swing.JRadioButton cliente;
    private javax.swing.JLabel conciliacion_texto;
    private javax.swing.JPanel conciliación;
    private javax.swing.JLabel gif_label;
    private javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton normal;
    private javax.swing.JLabel recordatorio;
    private javax.swing.JLabel selecciona_catalogo;
    private javax.swing.JLabel selecciona_conciliacion;
    // End of variables declaration//GEN-END:variables
}
