/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ase.polizas;

/**
 *
 * @author Rodriguez Santiago Yazmin L.
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texto_bienvenida_3 = new javax.swing.JLabel();
        texto_bienvenida_1 = new javax.swing.JLabel();
        texto_bienvenida_2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        texto_instrucciones = new javax.swing.JLabel();
        texto_instrucciones1 = new javax.swing.JLabel();
        texto_instrucciones2 = new javax.swing.JLabel();
        texto_instrucciones3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        texto_bienvenida_3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        texto_bienvenida_3.setForeground(new java.awt.Color(51, 51, 51));
        texto_bienvenida_3.setText("Lee detenidamente las instrucciones:");

        texto_bienvenida_1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        texto_bienvenida_1.setText("Bienvenido al Sistema Auxiliar de Pólizas");

        texto_bienvenida_2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        texto_bienvenida_2.setForeground(new java.awt.Color(51, 51, 51));
        texto_bienvenida_2.setText("En este sistema podrás generar tus pólizas de Ingresos y Egresos");

        texto_instrucciones.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        texto_instrucciones.setForeground(new java.awt.Color(51, 51, 51));
        texto_instrucciones.setText("- Verifica que los nombre de las cuentas se encuentren correctos y en la columna de");

        texto_instrucciones1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        texto_instrucciones1.setForeground(new java.awt.Color(51, 51, 51));
        texto_instrucciones1.setText("- Verifica que los archivos que ingresas tenga la información necesaria en la primer hoja");

        texto_instrucciones2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        texto_instrucciones2.setForeground(new java.awt.Color(51, 51, 51));
        texto_instrucciones2.setText("- Verifica que seleccionas los archivos de un mismo periodo");

        texto_instrucciones3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        texto_instrucciones3.setForeground(new java.awt.Color(51, 51, 51));
        texto_instrucciones3.setText("concepto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto_instrucciones2)
                    .addComponent(texto_instrucciones1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(texto_instrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texto_instrucciones3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(texto_bienvenida_1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_bienvenida_3)
                            .addComponent(texto_bienvenida_2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(texto_bienvenida_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(texto_bienvenida_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto_bienvenida_3)
                .addGap(27, 27, 27)
                .addComponent(texto_instrucciones1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_instrucciones)
                    .addComponent(texto_instrucciones3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto_instrucciones2)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel texto_bienvenida_1;
    private javax.swing.JLabel texto_bienvenida_2;
    private javax.swing.JLabel texto_bienvenida_3;
    private javax.swing.JLabel texto_instrucciones;
    private javax.swing.JLabel texto_instrucciones1;
    private javax.swing.JLabel texto_instrucciones2;
    private javax.swing.JLabel texto_instrucciones3;
    // End of variables declaration//GEN-END:variables
}
